### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by anishathalye** [cleanlab/cleanlab#299]
We should switch to CD using GitHub Actions, where we:

- Automatically build nightly releases and push to Conda and PyPI
- Automatically build and release on Conda and PyPI when a new tag is pushed to this git repo

This will be especially useful once we have a more complicated build process (#297).

**Comment by elisno** [comment]
Something along these lines?
(Based on [this starter workflow](https://github.com/actions/starter-workflows/blob/main/ci/python-publish.yml))

```yml
name: Upload Python Package

on:
  release:
    types: [published]
  schedule:
    cron: '0 3 * * *' # Whenever the nightly build needs to run.

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade pip # What build dependencies are needed?

    - name: Build package
      run: # What build command?

    # I think this handles both release tags and nightly releases
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@717ba43cfbb0387f6ce311b169a825772f54d295 # or pin to some other SHA
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
```
